services:
  redis:
    image: redis:7
    container_name: phanto-redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: phanto-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - cluster.routing.allocation.disk.watermark.low=95%
      - cluster.routing.allocation.disk.watermark.high=97%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: phanto-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

  rabbitmq:
    image: rabbitmq
    container_name: phanto-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rmq_data:/var/lib/rabbitmq

  mongo:
    image: mongo:6
    container_name: phanto-mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - mongo_data:/data/db

volumes:
  es_data:
  rmq_data:
  mongo_data:

networks:
  elk:
    driver: bridge
  rmq:
    driver: bridge
  mongo:
    driver: bridge
